<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class CustomerRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            //
            "name" => "required | min:2 | max:16 | regex:/^[a-zA-Z ]+$/",
            "phone"=> "required | min:10 | max:12 | regex:/^\\d{10}$/",
            "acc_no"=> ['required',Rule::unique('customers','acc_no'),' min:6 ',' max:16  ',' regex:/^[0-9]+$/'],
            //"acc_no"=> "required | unique:customers | min:6 | max:16  | regex:/^[0-9]+$/",
            "ifsc"=>"required | regex:/^[A-Z]{4}0[A-Z0-9]{6}$/",
            "bank"=> "required | min:3 | max: 48 | regex:/^[a-zA-Z ]+$/",
        ];
    }

    public function messages()
    {
        return [
            'acc_no.unique'=>'Already account is registered',
        ]; // TODO: Change the autogenerated stub
    }


}
